#凡是微服务一定要写端口号和微服务名称
server:
  port: 8001

spring:
  application:
    name: cloud-payment-service     #这个名字很重要 微服务之间的调用就用它
  datasource:     # 数据源配置 spring整合 druid 数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?serverTimezone=GMT
    username: root
    password: root

  devtools: #热部署以下这两个配置 必须写上 否则 页面不能正常显示
    restart:
      poll-interval: 2s
      quiet-period: 1s

mybatis: # mybatis配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

eureka:

  instance:
    instance-id: payment8001    #这个配置会替换 status 的默认名称 (WIN10-805131716:cloud-payment-service:8001)
    prefer-ip-address: true     #访问路径(status)可以显示ip地址

    lease-renewal-interval-in-seconds: 1    #客户端向服务端发送心跳的间隔时间 单位 s (默认30s)
    lease-expiration-duration-in-seconds: 2   #eureka服务端接收到心跳时间的上限2s 超过后将剔除 (默认90s)

  client:
    register-with-eureka: true    # 1.0表示是否将自己注册到eureka服务器中
    fetch-registry: true   # 2.0是否从eureka server 中抓取已有的信息 默认true，单节点无所谓2.0集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka    #单机版注册服务地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka    #集群版注册地址




#热部署生效
#  spring.devtools.restart.enabled=true

#设置重启的目录,添加那个目录的文件需要restart
#  spring.devtools.restart.additional-paths=src/main/java

# 排除那个目录的文件不需要restart
#spring.devtools.restart.exclude=static/**,public/**

#classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude=WEB-INF/**

#  spring.devtools.restart.poll-interval=2s
# spring.devtools.restart.quiet-period=1s
