server:
  port: 7001

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka7001.com          #eureka 服务端的实例名称
  client:
    register-with-eureka: false   #不向注册中心注册自己
    fetch-registry: false         #我的职责是维护实例 并不需要去检索服务
    service-url:                  #设置与eureka server 交互的地址   查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    enable-self-preservation: false   #取消保护机制 保证不可用的服务被及时剔除
    eviction-interval-timer-in-ms: 2000   #租约到期之后(租约的设定在于服务模块默认90s) 剔除时间间隔 2s